<?php
declare(strict_types=1);use DecisionRules\AuditRepository;
require __DIR__.'/_auth.php';$auth->requireAnyRole(['ADMIN','RULE_EDITOR','RULE_APPROVER','VIEWER']);$repo=new AuditRepository($pdo);
$filters=[];foreach(['date_from','date_to','user','event_type','category','rule_set_version','rule_set_id','rule_code','search'] as $key)$filters[$key]=trim((string)($_GET[$key]??''));
$page=max(1,(int)($_GET['page']??1));$result=$repo->page($filters,$page,50);$title='Audit Log';$activePage='audit';require __DIR__.'/partials/header.php';
$query=function(int $p)use($filters):string{return http_build_query(array_filter($filters,fn($v)=>$v!=='')+['page'=>$p]);};
?>
<section class="panel audit-filters"><div class="panel-head"><div><h2>Change history</h2><p>Read-only security and business event trail.</p></div></div><form method="get" class="filter-grid">
<?php foreach(['date_from'=>'Date From','date_to'=>'Date To'] as $name=>$label):?><label><?=$label?><input type="date" name="<?=$name?>" value="<?=e($filters[$name])?>"></label><?php endforeach;?>
<label>User<input name="user" value="<?=e($filters['user'])?>" placeholder="username"></label><label>Event Type<select name="event_type"><option value="">All</option><?php foreach($repo->eventTypes() as $type):?><option <?=$filters['event_type']===$type?'selected':''?>><?=e($type)?></option><?php endforeach;?></select></label>
<label>Category<select name="category"><?php foreach([''=>'All','rule_changes'=>'Rule Changes','rule_sets'=>'Rule Sets','users'=>'Users & Access','authentication'=>'Authentication'] as $v=>$l):?><option value="<?=e($v)?>" <?=$filters['category']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label>
<label>Rule Set Version<input type="number" min="1" name="rule_set_version" value="<?=e($filters['rule_set_version'])?>"></label><label>Rule Code<input name="rule_code" value="<?=e($filters['rule_code'])?>"></label><label>Search<input name="search" value="<?=e($filters['search'])?>" placeholder="username / rule code / event"></label>
<div class="filter-actions"><button class="btn primary">Apply filters</button><a class="btn secondary" href="audit.php">Reset</a></div></form></section>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Date / Time</th><th>User</th><th>Event</th><th>Object</th><th>Description</th><th>IP Address</th><th>Details</th></tr></thead><tbody>
<?php foreach($result['rows'] as $event):$d=$event['details_data'];?><tr><td><?=e(date('d.m.Y H:i',strtotime($event['created_at'])))?></td><td><?=e($event['username']?:'System')?></td><td><span class="badge audit-<?=e(strtolower(str_replace(' ','-',$event['category'])))?>"><?=e($event['label'])?></span></td><td><?php if(!empty($d['rule_code'])):?><strong>Rule <?=e($d['rule_code'])?></strong><?php endif;?><?php if(!empty($d['rule_set_version'])):?><br><a class="rule-code" href="rule_set_view.php?id=<?=(int)($d['rule_set_id']??$event['entity_id'])?>">Rule Set v<?=(int)$d['rule_set_version']?></a><?php elseif($event['entity_type']):?><?=e(ucwords(str_replace('_',' ',$event['entity_type'])))?> #<?=(int)$event['entity_id']?><?php endif;?></td><td><?=e($event['label'])?></td><td><?=e($event['ip_address']?:'—')?></td><td><a class="rule-code" href="audit_view.php?id=<?=(int)$event['id']?>">View</a></td></tr><?php endforeach;?>
<?php if(!$result['rows']):?><tr><td colspan="7" class="empty">No audit events match these filters.</td></tr><?php endif;?></tbody></table></div>
<nav class="pagination" aria-label="Pagination"><span><?=number_format($result['total'])?> events</span><div><?php if($page>1):?><a class="btn tiny" href="?<?=e($query($page-1))?>">← Previous</a><?php endif;?><span>Page <?=$page?> of <?=$result['pages']?></span><?php if($page<$result['pages']):?><a class="btn tiny" href="?<?=e($query($page+1))?>">Next →</a><?php endif;?></div></nav></section>
<?php require __DIR__.'/partials/footer.php';?>
