<?php
declare(strict_types=1);use DecisionRules\EvaluationLogRepository;
require __DIR__.'/_auth.php';$auth->requireAnyRole(['ADMIN','RULE_EDITOR','RULE_APPROVER','VIEWER']);$repo=new EvaluationLogRepository($pdo);
$filters=[];foreach(['date_from','date_to','request_id','decision','stage','rule_set_version','rule_code','result','http_status'] as $k)$filters[$k]=trim((string)($_GET[$k]??''));$page=max(1,(int)($_GET['page']??1));$result=$repo->page($filters,$page,50);
$title='Evaluations';$activePage='evaluations';require __DIR__.'/partials/header.php';$query=fn(int $p)=>http_build_query(array_filter($filters,fn($v)=>$v!=='')+['page'=>$p]);
?>
<section class="panel"><div class="panel-head"><div><h2>API Request &amp; Response Log</h2><p>Read-only journal of Decision Rules evaluations.</p></div></div><form method="get" class="filter-grid">
<label>Date From<input type="date" name="date_from" value="<?=e($filters['date_from'])?>"></label><label>Date To<input type="date" name="date_to" value="<?=e($filters['date_to'])?>"></label><label>Request ID<input name="request_id" value="<?=e($filters['request_id'])?>"></label><label>Decision<input name="decision" value="<?=e($filters['decision'])?>"></label><label>Stage<input name="stage" value="<?=e($filters['stage'])?>"></label><label>Rule Set Version<input type="number" min="1" name="rule_set_version" value="<?=e($filters['rule_set_version'])?>"></label><label>Rule Code<input name="rule_code" value="<?=e($filters['rule_code'])?>"></label><label>Result<select name="result"><option value="">All</option><option value="success" <?=$filters['result']==='success'?'selected':''?>>Success</option><option value="error" <?=$filters['result']==='error'?'selected':''?>>Error</option></select></label><label>HTTP Status<input type="number" name="http_status" value="<?=e($filters['http_status'])?>"></label><div class="filter-actions"><button class="btn primary">Apply filters</button><a class="btn secondary" href="evaluations.php">Reset</a></div></form></section>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Time</th><th>Request ID</th><th>Result</th><th>Decision</th><th>Stage</th><th>Rule Set</th><th>Matched Rules</th><th>HTTP</th><th>Time ms</th><th>Details</th></tr></thead><tbody><?php foreach($result['rows'] as $row):?><tr><td><?=e(date('d.m.Y H:i:s',strtotime($row['received_at'])))?></td><td><code title="<?=e($row['request_id'])?>"><?=e(substr($row['request_id'],0,8))?>…</code></td><td><span class="badge <?=$row['log_status']==='COMPLETED'?'on':'off'?>"><?=e($row['success']===null?$row['log_status']:((int)$row['success']?'SUCCESS':'ERROR'))?></span></td><td><?=e($row['decision']?:'—')?></td><td><?=e(str_replace('_',' ',$row['stage']?:'—'))?></td><td><?=$row['rule_set_version']?'v'.(int)$row['rule_set_version']:'—'?></td><td><?php $codes=array_column($row['matched_rules_data'],'rule_code');?><?=e($codes?implode(', ',$codes):'—')?></td><td><?=(int)$row['http_status']?:'—'?></td><td><?=$row['execution_time_ms']!==null?e(number_format((float)$row['execution_time_ms'],3)).' ms':'—'?></td><td><a class="rule-code" href="evaluation_view.php?id=<?=(int)$row['id']?>">View</a></td></tr><?php endforeach;?><?php if(!$result['rows']):?><tr><td colspan="10" class="empty">No evaluations match these filters.</td></tr><?php endif;?></tbody></table></div><nav class="pagination"><span><?=number_format($result['total'])?> evaluations</span><div><?php if($page>1):?><a class="btn tiny" href="?<?=e($query($page-1))?>">← Previous</a><?php endif;?><span>Page <?=$page?> of <?=$result['pages']?></span><?php if($page<$result['pages']):?><a class="btn tiny" href="?<?=e($query($page+1))?>">Next →</a><?php endif;?></div></nav></section>
<?php require __DIR__.'/partials/footer.php';?>
