<?php
declare(strict_types=1);
use DecisionRules\Database; use DecisionRules\RuleRepository;
require_once __DIR__.'/../src/bootstrap.php';
$repo=new RuleRepository(Database::connect(dirname(__DIR__))); $id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'id',FILTER_VALIDATE_INT); $rule=$id?$repo->find($id):null; $errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $code=trim((string)($_POST['rule_code']??'')); $stage=(string)($_POST['stage_name']??''); $pd=filter_var($_POST['avg_actual_pd']??null,FILTER_VALIDATE_FLOAT); $priority=filter_var($_POST['priority']??null,FILTER_VALIDATE_INT);
 if(!preg_match('/^[A-Z0-9_-]{2,50}$/',$code))$errors[]='Rule code must contain 2–50 uppercase letters, numbers, underscores, or hyphens.'; if(!in_array($stage,RuleRepository::STAGES,true))$errors[]='Select a valid stage.'; if($pd===false||$pd<0||$pd>100)$errors[]='Average Actual PD must be between 0 and 100.'; if($priority===false||$priority<0)$errors[]='Priority must be a non-negative integer.';
 $conditions=[]; foreach((array)($_POST['conditions']??[]) as $condition){$field=strtoupper(trim((string)($condition['field_name']??'')));$operator=(string)($condition['operator']??'');$value=trim((string)($condition['value']??''));if(!preg_match('/^[A-Z][A-Z0-9_]{0,190}$/',$field)){$errors[]='Every field name must use uppercase letters, numbers, and underscores.';continue;}if(!in_array($operator,RuleRepository::OPERATORS,true)){$errors[]='Invalid condition operator.';continue;}if(!in_array($operator,['IS_NULL','IS_NOT_NULL'],true)&&$value===''){$errors[]='Condition values cannot be empty for this operator.';continue;}if(in_array($operator,['IN','NOT_IN'],true)&&str_starts_with($value,'[')&&!is_array(json_decode($value,true)))$errors[]='List values must be a valid JSON array or a single value.';$conditions[]=['field_name'=>$field,'operator'=>$operator,'value'=>in_array($operator,['IS_NULL','IS_NOT_NULL'],true)?null:$value];}
 if(!$conditions)$errors[]='Add at least one valid condition.';
 if(!$errors){try{$saved=$repo->save(['rule_code'=>$code,'stage_name'=>$stage,'avg_actual_pd'=>$pd,'priority'=>$priority,'active'=>isset($_POST['active'])?1:0,'description'=>trim((string)($_POST['description']??''))?:null],$conditions,$id?:null);$_SESSION['flash']=$id?'Rule updated.':'Rule created.';redirect('rule_view.php?id='.$saved);}catch(Throwable $e){$errors[]='Unable to save the rule. Make sure the rule code is unique.';}}
 $rule=['id'=>$id,'rule_code'=>$code,'stage_name'=>$stage,'avg_actual_pd'=>$pd,'priority'=>$priority,'active'=>isset($_POST['active']),'description'=>$_POST['description']??'','conditions'=>$conditions];
}
$rule??=['id'=>null,'rule_code'=>'','stage_name'=>'HARD_REFUSAL_STAGE','avg_actual_pd'=>'','priority'=>10,'active'=>1,'description'=>'','conditions'=>[['field_name'=>'','operator'=>'>','value'=>'']]]; $title=$id?'Edit Rule':'Add Rule';$activePage=$id?'rules':'add';require __DIR__.'/partials/header.php';
?>
<?php foreach($errors as $error): ?><div class="alert error"><?= e($error) ?></div><?php endforeach; ?>
<form method="post" class="rule-form"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><?php if($id): ?><input type="hidden" name="id" value="<?= (int)$id ?>"><?php endif; ?>
<section class="panel form-section"><div class="panel-head"><div><h2>Rule details</h2><p>Define its identity, evaluation stage, and order.</p></div></div><div class="form-grid"><label>Rule Code<input required name="rule_code" value="<?= e($rule['rule_code']) ?>" placeholder="HR_008"></label><label>Stage<select name="stage_name"><?php foreach(RuleRepository::STAGES as $stage): ?><option <?= $rule['stage_name']===$stage?'selected':'' ?> value="<?= e($stage) ?>"><?= e(str_replace('_',' ',$stage)) ?></option><?php endforeach; ?></select></label><label>Average Actual PD (%)<input required type="number" min="0" max="100" step="0.0001" name="avg_actual_pd" value="<?= e($rule['avg_actual_pd']) ?>"></label><label>Priority<input required type="number" min="0" name="priority" value="<?= e($rule['priority']) ?>"></label><label class="full">Description<textarea name="description" rows="3" placeholder="Explain the purpose of this rule…"><?= e($rule['description']) ?></textarea></label><label class="check full"><input type="checkbox" name="active" value="1" <?= $rule['active']?'checked':'' ?>><span>Active and available to the evaluation API</span></label></div></section>
<section class="panel form-section"><div class="panel-head"><div><h2>Condition builder</h2><p>Every condition must match (AND). Lists accept a JSON array or one value.</p></div><button class="btn secondary" type="button" data-add-condition>+ Add condition</button></div><div class="condition-builder" data-condition-builder><?php foreach($rule['conditions'] as $i=>$c): ?><div class="condition-row"><label>Field Name<input required name="conditions[<?= $i ?>][field_name]" value="<?= e($c['field_name']) ?>" placeholder="AGE"></label><label>Operator<select name="conditions[<?= $i ?>][operator]"><?php foreach(RuleRepository::OPERATORS as $op): ?><option <?= $c['operator']===$op?'selected':'' ?>><?= e($op) ?></option><?php endforeach; ?></select></label><label>Value<input name="conditions[<?= $i ?>][value]" value="<?= e($c['value']) ?>" placeholder='31.03 or ["Yes"]'></label><button type="button" class="remove" data-remove aria-label="Remove">×</button></div><?php endforeach; ?></div></section><div class="form-actions"><a class="btn secondary" href="rules.php">Cancel</a><button class="btn primary" type="submit">Save Rule</button></div></form>
<template id="condition-template"><div class="condition-row"><label>Field Name<input required data-name="field_name" placeholder="FIELD_NAME"></label><label>Operator<select data-name="operator"><?php foreach(RuleRepository::OPERATORS as $op): ?><option><?= e($op) ?></option><?php endforeach; ?></select></label><label>Value<input data-name="value" placeholder='Value or ["A","B"]'></label><button type="button" class="remove" data-remove>×</button></div></template><?php require __DIR__.'/partials/footer.php'; ?>
