<?php
declare(strict_types=1);
use DecisionRules\Database; use DecisionRules\RuleRepository;
require_once __DIR__.'/../src/bootstrap.php'; $id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT); $repo=new RuleRepository(Database::connect(dirname(__DIR__))); $rule=$id?$repo->find($id):null; if(!$rule){http_response_code(404);exit('Rule not found');}
$title=$rule['rule_code']; $activePage='rules'; require __DIR__.'/partials/header.php';
?>
<section class="rule-hero panel"><div><span class="badge stage <?= e(strtolower(explode('_',$rule['stage_name'])[0])) ?>"><?= e(str_replace('_',' ',$rule['stage_name'])) ?></span><h2><?= e($rule['rule_code']) ?></h2><p><?= e($rule['description']?:'No description provided.') ?></p></div><a class="btn secondary" href="rule_edit.php?id=<?= (int)$rule['id'] ?>">Edit rule</a></section>
<section class="detail-grid"><article class="panel metric"><small>Average Actual PD</small><strong><?= e(number_format((float)$rule['avg_actual_pd'],2)) ?>%</strong></article><article class="panel metric"><small>Priority</small><strong><?= (int)$rule['priority'] ?></strong></article><article class="panel metric"><small>Status</small><strong><span class="badge <?= $rule['active']?'on':'off' ?>"><?= $rule['active']?'Active':'Inactive' ?></span></strong></article></section>
<section class="panel"><div class="panel-head"><div><h2>Conditions</h2><p>All conditions are connected with logical AND.</p></div></div><ol class="condition-list"><?php foreach($rule['conditions'] as $i=>$c): ?><li><span class="and"><?= $i?'AND':'IF' ?></span><code><?= e($c['field_name']) ?></code><strong><?= e($c['operator']) ?></strong><?php if(!in_array($c['operator'],['IS_NULL','IS_NOT_NULL'],true)): ?><code><?= e($c['value']) ?></code><?php endif; ?></li><?php endforeach; ?></ol></section><?php require __DIR__.'/partials/footer.php'; ?>
