<?php
declare(strict_types=1);
use DecisionRules\Database; use DecisionRules\RuleRepository; use DecisionRules\AuditRepository;
require __DIR__.'/_auth.php'; $auth->requireAnyRole(['ADMIN','RULE_EDITOR','RULE_APPROVER','VIEWER']); $id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT); $repo=new RuleRepository($pdo); $rule=$id?$repo->find($id):null; if(!$rule){http_response_code(404);exit('Rule not found');}
$title=$rule['rule_code']; $activePage='rules'; require __DIR__.'/partials/header.php';
?>
<section class="rule-hero panel"><div><span class="badge stage <?= e(strtolower(explode('_',$rule['stage_name'])[0])) ?>"><?= e(str_replace('_',' ',$rule['stage_name'])) ?></span><h2><?= e($rule['rule_code']) ?></h2><p><?= e($rule['description']?:'No description provided.') ?></p></div><?php if($auth->hasRole('RULE_EDITOR')&&$pdo->query('SELECT status FROM rule_sets WHERE id='.(int)$rule['rule_set_id'])->fetchColumn()==='DRAFT'):?><a class="btn secondary" href="rule_edit.php?id=<?= (int)$rule['id'] ?>">Edit rule</a><?php endif;?></section>
<section class="detail-grid"><article class="panel metric"><small>Rule ID</small><strong>#<?= (int)$rule['id'] ?></strong><?php if($rule['source_rule_id']!==null):?><small>Based on Rule ID #<?= (int)$rule['source_rule_id'] ?></small><?php endif;?></article><article class="panel metric"><small>Average Actual PD</small><strong><?= e(number_format((float)$rule['avg_actual_pd'],2)) ?>%</strong></article><article class="panel metric"><small>Priority</small><strong><?= (int)$rule['priority'] ?></strong></article><article class="panel metric"><small>Status</small><strong><span class="badge <?= $rule['active']?'on':'off' ?>"><?= $rule['active']?'Active':'Inactive' ?></span></strong></article></section>
<section class="panel"><div class="panel-head"><div><h2>Conditions</h2><p>All conditions are connected with logical AND.</p></div></div><ol class="condition-list"><?php foreach($rule['conditions'] as $i=>$c): ?><li><span class="and"><?= $i?'AND':'IF' ?></span><code><?= e($c['field_name']) ?></code><strong><?= e($c['operator']) ?></strong><?php if(!in_array($c['operator'],['IS_NULL','IS_NOT_NULL'],true)): ?><code><?= e($c['value']) ?></code><?php endif; ?></li><?php endforeach; ?></ol></section><?php $history=(new AuditRepository($pdo))->ruleHistory((int)$rule['rule_set_id'],(string)$rule['rule_code'],[(int)$rule['id'],(int)($rule['source_rule_id']??0)],20);?><section class="panel"><div class="panel-head"><div><h2>Change History</h2><p>History follows the business rule across immutable database rows.</p></div><a href="audit.php?rule_set_id=<?=(int)$rule['rule_set_id']?>&amp;rule_code=<?=urlencode($rule['rule_code'])?>">View full audit history</a></div><div class="audit-timeline rich"><?php foreach($history as $event):?><article><time><?=e(date('d.m.Y H:i',strtotime($event['created_at'])))?></time><div><strong><?=e($event['label'])?></strong><small><?=e($event['username']?:'System')?></small><?php require __DIR__.'/partials/audit_event.php';?></div><a href="audit_view.php?id=<?=(int)$event['id']?>">View</a></article><?php endforeach;?><?php if(!$history):?><p class="empty">No recorded changes.</p><?php endif;?></div></section><?php require __DIR__.'/partials/footer.php'; ?>
